close all;
clear all;
clc;

carrega_series;

serie = djia;
figure;
semilogy(serie);
xlabel('dias');
ylabel('DJIA');
grid on; axis tight;
print -depsc 'fig_djia';
figure;
plot(price2ret(serie)-mean(price2ret(serie)));
xlabel('dias');
ylabel('Retorno DJIA');
grid on; axis tight;
print -depsc 'fig_djia_ret';

serie = sp500;
figure;
semilogy(serie);
xlabel('dias');
ylabel('S&P500');
grid on; axis tight;
print -depsc 'fig_sp500';
figure;
plot(price2ret(serie)-mean(price2ret(serie)));
xlabel('dias');
ylabel('Retorno S&P500');
grid on; axis tight;
print -depsc 'fig_sp500_ret';

serie = ibov;
figure;
semilogy(serie);
xlabel('dias');
ylabel('Ibovespa');
grid on; axis tight;
print -depsc 'fig_ibov';
figure;
plot(price2ret(serie)-mean(price2ret(serie)));
xlabel('dias');
ylabel('Retorno Ibovespa');
grid on; axis tight;
print -depsc 'fig_ibov_ret';

serie = peto;
figure;
semilogy(serie);
xlabel('dias');
ylabel('Petr4 (abertura)');
grid on; axis tight;
print -depsc 'fig_peto';
figure;
plot(price2ret(serie)-mean(price2ret(serie)));
xlabel('dias');
ylabel('Retorno Petr4 (abertura)');
grid on; axis tight;
print -depsc 'fig_peto_ret';

serie = peth;
figure;
semilogy(serie);
xlabel('dias');
ylabel('Petr4 (máxima)');
grid on; axis tight;
print -depsc 'fig_peth';
figure;
plot(price2ret(serie)-mean(price2ret(serie)));
xlabel('dias');
ylabel('Retorno Petr4 (máxima)');
grid on; axis tight;
print -depsc 'fig_peth_ret';

serie = petl;
figure;
semilogy(serie);
xlabel('dias');
ylabel('Petr4 (mínima)');
grid on; axis tight;
print -depsc 'fig_petl';
figure;
plot(price2ret(serie)-mean(price2ret(serie)));
xlabel('dias');
ylabel('Retorno Petr4 (mínima)');
grid on; axis tight;
print -depsc 'fig_petl_ret';

serie = petc;
figure;
semilogy(serie);
xlabel('dias');
ylabel('Petr4 (fechamento)');
grid on; axis tight;
print -depsc 'fig_petc';
figure;
plot(price2ret(serie)-mean(price2ret(serie)));
xlabel('dias');
ylabel('Retorno Petr4 (fechamento)');
grid on; axis tight;
print -depsc 'fig_petc_ret';
